version: "3"
services: 
  node:
    build: .
    container_name: next-demo-1
    ports:
      - "3000:3000"
    restart: always
    environment: 
      - NODE_ENV=production
    command: npm run start
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    container_name: nginx-node
    restart: always
    volumes: 
      - "/www/demo/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks: 
      - "demo-network-group"
    links:
      - "node"
    depends_on: 
      - "node"
  networks: 
    demo-network-group:
      driver: bridge