version: "3"
services: 
  node:
    build: .
    container_name: next-demo-1
    ports:
      - "3000:3000"
    restart: always
    environment: 
      - NODE_ENV=production
    command: npm run start